#!/usr/bin/env python3
"""Refetch BTC-USD / S&P 500 prices and rewrite the DATA block in index.html."""
import datetime
import json
import re
import urllib.parse
import urllib.request
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_HTML = REPO_ROOT / "index.html"

PERIODS = [
    ("Weekly", 7),
    ("Monthly", 30),
    ("Quarterly", 91),
    ("Yearly", 365),
    ("5-Year", 365 * 5 + 1),
]


def fetch_series(symbol):
    url = (
        "https://query1.finance.yahoo.com/v8/finance/chart/"
        + urllib.parse.quote(symbol, safe="")
        + "?range=5y&interval=1d"
    )
    req = urllib.request.Request(url, headers={"User-Agent": "Mozilla/5.0"})
    with urllib.request.urlopen(req, timeout=30) as resp:
        data = json.load(resp)
    result = data["chart"]["result"][0]
    timestamps = result["timestamp"]
    closes = result["indicators"]["quote"][0]["close"]
    points = [
        (datetime.datetime.fromtimestamp(t, tz=datetime.timezone.utc).date(), c)
        for t, c in zip(timestamps, closes)
        if c is not None
    ]
    return points


def nearest(points, target):
    return min(points, key=lambda p: abs((p[0] - target).days))


def build_data():
    btc = fetch_series("BTC-USD")
    spx = fetch_series("^GSPC")

    today_btc = btc[-1]
    today_spx = spx[-1]

    periods = []
    for label, days in PERIODS:
        target = today_btc[0] - datetime.timedelta(days=days)
        bp = nearest(btc, target)
        sp = nearest(spx, target)
        btc_ret = (today_btc[1] / bp[1] - 1) * 100
        spx_ret = (today_spx[1] / sp[1] - 1) * 100
        periods.append(
            {
                "label": label,
                "btcDate": bp[0].isoformat(),
                "btcStart": round(bp[1], 2),
                "btcRet": round(btc_ret, 2),
                "spxDate": sp[0].isoformat(),
                "spxStart": round(sp[1], 2),
                "spxRet": round(spx_ret, 2),
                "delta": round(btc_ret - spx_ret, 2),
            }
        )

    current = {
        "btc": {"date": today_btc[0].isoformat(), "price": round(today_btc[1], 2)},
        "spx": {"date": today_spx[0].isoformat(), "price": round(today_spx[1], 2)},
    }
    return current, periods


def js_obj(d):
    return "{ " + ", ".join(f"{k}: {js_val(v)}" for k, v in d.items()) + " }"


def js_val(v):
    if isinstance(v, dict):
        return js_obj(v)
    if isinstance(v, str):
        return json.dumps(v)
    return repr(v)


def render_block(current, periods):
    lines = []
    lines.append("  // DATA_START — regenerated by scripts/update_data.py, do not hand-edit")
    lines.append(f"  var current = {js_obj(current)};")
    lines.append("")
    lines.append("  var periods = [")
    for i, p in enumerate(periods):
        comma = "," if i < len(periods) - 1 else ""
        lines.append(
            "    { label: %s, btcDate: %s, btcStart: %s, btcRet: %s, "
            "spxDate: %s, spxStart: %s, spxRet: %s, delta: %s }%s"
            % (
                json.dumps(p["label"]),
                json.dumps(p["btcDate"]),
                p["btcStart"],
                p["btcRet"],
                json.dumps(p["spxDate"]),
                p["spxStart"],
                p["spxRet"],
                p["delta"],
                comma,
            )
        )
    lines.append("  ];")
    lines.append("  // DATA_END")
    return "\n".join(lines)


def main():
    current, periods = build_data()
    new_block = render_block(current, periods)

    html = INDEX_HTML.read_text(encoding="utf-8")
    pattern = re.compile(r"  // DATA_START.*?// DATA_END", re.DOTALL)
    if not pattern.search(html):
        raise SystemExit("DATA_START/DATA_END markers not found in index.html")
    html = pattern.sub(new_block.replace("\\", "\\\\"), html, count=1)
    INDEX_HTML.write_text(html, encoding="utf-8")
    print("Updated index.html with data as of", current["btc"]["date"])


if __name__ == "__main__":
    main()
